services:
  postgres:
    image: postgres:17.6-trixie
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  database_data:
    driver: local
